# Default sdr configs. These are included in the binary.

# rtlsdr
[[sdrs]]
driver = "rtlsdr"

[[sdrs.gain]]
key = "TUNER"
value = 49.6

[[sdrs.setting]]
key = "biastee"
value = "true"

# HackRF
[[sdrs]]
driver = "hackrf"

[[sdrs.gain]]
key = "LNA"
value = 40.0

[[sdrs.gain]]
key = "VGA"
value = 52.0
