# Default sdr configs. These are included in the binary.

# rtlsdr
[[sdrs]]
driver = "rtlsdr"

[[sdrs.gain]]
key = "TUNER"
value = 49.6

# HackRF
[[sdrs]]
driver = "hackrf"

[[sdrs.gain]]
key = "LNA"
value = 40.0

[[sdrs.gain]]
key = "VGA"
value = 52.0

# USRP B210 (uhd)
# NOT TESTED(see https://github.com/rsadsb/dump1090_rs/issues/23)
#[[sdrs]]
#driver = "udh"
#channel = 0
#
#[[sdrs.gain]]
#key = "example"
#value = 0.0
#
#[sdrs.antenna]
#name = "RX"
