on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

name: binaries

jobs:
  # release binaries
  release-bins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@d76c2a93c593483c9892fd8d2538734f73ed8588 # stable
        with:
          target: ${{ matrix.targets }}
      - run: cargo install cargo-quickinstall
      - run: cargo quickinstall cross@0.2.5 --force
      - run: cross build --workspace --locked --release --target ${{ matrix.targets }}

      - name: archive
        run: |
          tar -czvf dump1090_rs-${{ matrix.targets }}.tar.gz \
              -C target/${{ matrix.targets }}/release/ dump1090_rs

      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: dump1090_rs-${{ matrix.targets }}.tar.gz
          path: dump1090_rs-${{ matrix.targets }}.tar.gz

      - name: Upload binary to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dump1090_rs-${{ matrix.targets }}.tar.gz
          asset_name: dump1090_rs-${{ github.ref_name }}-${{ matrix.targets }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
